### PR TITLE
include db-specific dependencies from specific var files

### PR DESCRIPTION
**Pull request by bverschueren**
- move  hardcoded MariaDB dependency to var file
- add PostgreSQL dependency (libpqxx-devel) to similar var file
- include var file based on _redmine_sql_driver_ variable

### CODE REVIEW

**Review by bngsudheer — CHANGES_REQUESTED** [review]
Thanks for the PR. It looks good. I have a small request. All role variables have the prefix redmine_. Seeing sql_driver_dependencies as an internal variable,  I would rename it to _sql_driver_dependencies or redmine_sql_driver_dependencies.

**Comment by bngsudheer** [comment]
I am curious. I didn't come across any issue while deploying with PostgreSQL driver. What requires  libpqxx-devel?
EDIT: It turns out in my environment, postgresql-devel was already installed on the system. This role did not show any errors.

**Comment by bngsudheer** [comment]
I have added a test for Redmine installation with PostgreSQL. Only postgresql-devel was needed. Please see https://github.com/bngsudheer/ansible-role-redmine/commit/607b0d43db28e72d92864c62fcded7e88b1fcab9. But I would still use your code to separate drivers. I'm still curious why libpqxx-devel is required.

**Comment by bverschueren** [comment]
Indeed, postgresql-devel is sufficient. I noticed the libpq dependency in the 'pg' gem docs (used by redmine), which I though were provided by libpqxx-devel in the fedora/centos repo, not realizing it should be simply postgresql-devel.

I've updated the names as you requested, prefixing internal var names with underscore.

**Review by bngsudheer — APPROVED** [review]
Merging.

**Pull request merged**
